# Generated by Django 2.0.6 on 2018-06-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscontral', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
